//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DWars.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DWARS_FORM                  101
#define IDS_EDIT                        102
#define IDS_TOOL                        103
#define IDM_MENU                        104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_DRUGS                130
#define IDD_DIALOG_NEW_GAME             131
#define IDD_DIALOG_JET                  132
#define IDD_DIALOG_QUANTITY             133
#define IDB_BITMAP_DRUGS                135
#define IDD_DIALOG_GUNS                 136
#define IDB_BITMAP_COAT                 136
#define IDD_DIALOG_FIGHT                137
#define IDD_DIALOG_FINANCE              138
#define IDB_SPLASH                      138
#define IDD_DIALOG_HISCORES             139
#define IDD_DIALOG_PLAYER_NAME          140
#define IDD_DIALOG_SELLING              141
#define IDD_PAGE_CONFIG_DRUGS           143
#define IDD_PAGE_CONFIG_COPS            144
#define IDD_PAGE_CONFIG_GAME            145
#define IDD_PAGE_ABOUT_GENERAL          146
#define IDD_PAGE_ABOUT_SOURCE           147
#define IDD_PAGE_ABOUT_GRAPHICS         148
#define IDC_BUTTON_EXIT                 1000
#define IDC_STATIC_DISTRICT             1001
#define IDC_LIST_SELL                   1001
#define IDC_LIST_SCORES                 1001
#define IDC_STATIC_CASH                 1002
#define IDC_LIST_BUY                    1002
#define IDC_SLIDER_AMOUNT               1002
#define IDC_BUTTON_GUNS                 1003
#define IDC_BUTTON_BUY                  1003
#define IDC_BUTTON_RUN                  1003
#define IDC_BUTTON_DEPOSIT              1003
#define IDC_BUTTON_MAX                  1003
#define IDC_BUTTON_SELL                 1004
#define IDC_BUTTON_FIGHT                1004
#define IDC_BUTTON_WITHDRAWL            1004
#define IDC_BUTTON_DUMP                 1005
#define IDC_BUTTON_BORROW               1005
#define IDC_BUTTON_CLEAR                1005
#define IDC_BUTTON_STAY                 1005
#define IDC_STATIC_BANK                 1006
#define IDC_LIST_DISTRICTS              1006
#define IDC_STATIC_DEBT                 1007
#define IDC_EDIT_NAME                   1007
#define IDC_STATIC_TOTAL                1008
#define IDC_STATIC_PLACE                1008
#define IDC_BUTTON_NEWGAME              1009
#define IDC_BUTTON_PAYBACK              1009
#define IDC_STATIC_DAY                  1010
#define IDC_BUTTON1                     1010
#define IDC_PROGRESS_HEALTH             1011
#define IDC_STATIC_PROFIT               1011
#define IDC_STATIC_WORTH                1012
#define IDC_LIST_DRUG_NUM               1013
#define IDC_EDIT_MIN_PRICE              1015
#define IDC_BUTTON_JET                  1016
#define IDC_EDIT_MAX_PRICE              1016
#define IDC_BUTTON_BUYSELL              1017
#define IDC_CHECK_CHEAP                 1017
#define IDC_BUTTON_FINANCES             1018
#define IDC_CHECK_EXPENSIVE             1018
#define IDC_BUTTON_ENDGAME              1019
#define IDC_EDIT_CHEAP_STRING           1019
#define IDC_EDIT_ESCAPE                 1020
#define IDC_EDIT_NUM                    1021
#define IDC_BUTTON_HOSPITAL             1021
#define IDC_EDIT_DEPUTY_ESCAPE          1021
#define IDC_SPIN_NUM                    1022
#define IDC_EDIT_HIT                    1022
#define IDC_STATIC_QUESTION             1023
#define IDC_EDIT_DEPUTY_HIT             1023
#define IDC_STATIC_FACT1                1024
#define IDC_EDIT_DROP                   1024
#define IDC_EDIT_JAIL                   1025
#define IDC_STATIC_COAT                 1026
#define IDC_EDIT_TOUGHNESS              1026
#define IDC_STATIC_MONEY                1027
#define IDC_EDIT_DAMAGE                 1027
#define IDC_STATIC_HEALTH               1029
#define IDC_CHECK_MESSAGES              1029
#define IDC_STATIC_GUNS                 1030
#define IDC_STATIC_RANK                 1030
#define IDC_EDIT_OUTPUT                 1031
#define IDC_LIST_GUNS                   1032
#define IDC_STATIC_TEXT                 1034
#define ID_FILE                         32771
#define IDS_CAP_FILE                    32773
#define ID_FILE_EXIT                    32774
#define ID_FILE_NEWGAME                 32775
#define ID_INFO_HIGHSCORES              32776
#define ID_FILE_OPENGAME                32782
#define ID_FILE_SAVEGAME                32783
#define ID_FILE_SAVEASGAME              32784
#define ID_INFO_SOUND                   32785
#define ID_INFO_SOUND_OFF               32790
#define ID_FILE_OPTIONS                 32792
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007
#define IDS_NEWGAME                     65008
#define IDS_OPENGAME                    65010
#define IDS_SAVEGAME                    65011
#define IDS_SOUND                       65012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32793
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
